### ISSUE TITLE
Null-Safety Support ?

### ISSUE THREAD

**Issue by ufukhawk** [anish-adm/trust_fall#9]
Hey! When will the null safety support arrive?

**Comment by Tomucha** [comment]
+1

@anish-adm Nice package, please make it up to date :-)

See also: https://www.google.com/search?q=please+meme&tbm=isch

**Comment by ufukhawk** [comment]
> +1
> 
> @anish-adm Nice package, please make it up to date :-)
> 
> See also: https://www.google.com/search?q=please+meme&tbm=isch

https://github.com/anish-adm/trust_fall/pull/10#issue-598945958
